/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 *
 * Allows to modify a bit in the bit band region
 * using its bit band alias to calculate bit to change.
 *
 */

#include <stdint.h>

#define ALIAS_BASE 0x22000000U
#define BIT_BAND_BASE 0x20000000U

int main(void) {
	//7th bit position of memory location

	/*
	 * 0x22000000 + [ 32 * 			(0x20000200 - 	0x20000000) ] +			  7 *   4
	 * alias_base +   [32 * (bit_band_memory_addr - bit_band_base_address)] + bit * 4
	 */


	//normal method
	uint8_t *ptr = (uint8_t*) 0x20000200;
	*ptr = 0xff;

	//clearing 7th bit of 0x2000200
	*ptr &= ~(1 << 7);

	//bit band method
	*ptr = 0xff;
	uint8_t *aliasPtr = (uint8_t*) (ALIAS_BASE
			+ (32 * (0x20000200 - BIT_BAND_BASE)) + (7 * 4));

	//clearing 7th bit of address 0x2000200
	*aliasPtr = 0;

	/* Loop forever */
	for (;;)
		;
}
