/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * Notes:
 * 	- Exception Entry Sequence:
 *
 * 		- 1. Pending bit set
 * 		- 2. Stacking and Vector fetch
 * 			- (psp or msp, if using seperate stack for thread and handler
 * 					then will be stacked using psp)
 * 		- 3. Entry into handler and active bet set
 * 		- 4. Clears pending bit status (processor does auto)
 * 		- 5. Processor mode changed to handler mode
 * 			- Uses MSP
 * 		-6.	 Handler code executes
 *
 * 	- Exception Exit Sequence:
 *
 * 		- 1. In Cortex M3/M4, Triggered using a special return addres (EXC_RETURN)
 * 		- 2. EXC_RETURN = generated during exception entry and is stored in LR
 * 				- Unlike normal C function which stores return address in LR
 * 		- 3. When EXC_RETURN is written into PC it triggers exception return
 *
 * 		- 4. EXC_RETURN: ** bit[2:3] = IMPORTANT
 *
 *				- bits[31:28] = EXC_RETURN indicator
 *				- bits[27:5] = 	Reserved (All 1)
 *				- bit[4] = Stack frame type
 *
 *				- bit[3] = Return mode
 *					- 1 = return to thread mode
 *					- 0 = return to handler mode
 *
 *				- bit[2] = Return stack
 *					- 1 = return with PSP
 *					- 0 = return with MSP
 *
 *				- bit[1] = Reserved (0)
 *				- bit[0] = Reserved (1)
 *
 *				- Example: 0xFFFFFF9
 *					- return to thread mode
 *					- get state from processor stack
 *					- return with MSP
 *
 *				- Example: 0xFFFFFFD
 *					- return to thread mode
 *					- get state from main stack
 *					- return with PSP
 *
 *				- LR is loaded into (MSP) if using both PSP and MSP
 *					- rest stack frame is stored into PSP
 *
 *
 */
#include<stdio.h>
#include<stdint.h>
/* This function executes in THREAD MODE of the processor */
void generate_interrupt() {

	uint32_t *pSTIR = (uint32_t*) 0xE000EF00;
	uint32_t *pISER0 = (uint32_t*) 0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= (1 << 3);

	/* Exception triggered:
	 *		2.STACKING OCCURS
	 *			- using MSP (Default) (never changed to PSP)
	 */
	*pSTIR = (3 & 0x1FF);

}
/* This function executes in THREAD MODE of the processor */
int main(void) {

	/*
	 * Change to PSP from MSP
	 */

	int controlReg  = 0x2;
	uint32_t pspValue = 0x20008000;

	__asm volatile("MSR PSP, %0"::"r"(pspValue));
	__asm volatile("MSR CONTROL,%0"::"r"(controlReg));

	printf("In thread mode : before interrupt\n");

	generate_interrupt();

	printf("In thread mode : after interrupt\n");

}

/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void) {
	printf("In handler mode : ISR\n");
}
