/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>

#define USART3_IRQNO 39

int main(void) {

	/**
	 * 1. Manually pend the pending bit for USART3 IRQ number in NVIC
	 * 		- in Real Scenario, bit is set automatically when
	 * 			peripheral issues interrupt
	 *
	 *	- NVIC_ISPR0 (OXE000E200) -> NVIC_ISPR7 (OXE000E21C)
	 * 	- NVIC_ISPR0 -> NVIC_ISPR7 = handle all 240 interrupts
	 * 		32 bits * 8 registers = 256 interrupts max
	 *
	 * 	- USART3 = IRQ39 -> 39th position in NVIC_ISPR70-NVIC_ISPR7
	 * 		39th position falls in register NVIC_ISPR71
	 * 		39 % 32 = 7th bit in NVIC_ISPR71
	 *
	 * 	*** ALL REGISTERS FOLLOW PATTERN
	 * 	*** NVIC_ISxR0 -> NVIC_ISPx7 = 240 interrupts
	 */

	/* NVIC_ISPR1 = NVIC_ISPR0(OXE000E200) + 4 (word size, 32 bits) */
	uint32_t volatile *const pNVIC_ISPR1 = (uint32_t*) (0xE000E200 + 4);

	//set 7th bit high for IRQ 39
	*pNVIC_ISPR1 |= (1 << (USART3_IRQNO % 32));

	/**
	 * 2. Enable the USART3 IRQ Number in NVIC
	 * Register: NVIC_ISER1 = NVIC_ISPR0(OXE000E100) + 4 (word size, 32 bits)
	 */

	uint32_t volatile *const pNVIC_ISER1 = (uint32_t*) (0xE000E100 + 4);

	*pNVIC_ISER1 |= (1 << (USART3_IRQNO % 32));

}

/**
 * Pending state is cleared when ISR is called
 * ENABLE USART3 ISR -> Located in startup file
 */
void USART3_IRQHandler(void) {
	printf("in USART3 ISR\n");
}

