/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

void assembly1() {

	__asm volatile("LDR R1, =#0x20001000");
	__asm volatile("LDR R2, =#0x20001004");

//	uint32_t volatile *const r1 = (uint32_t*) 0x20001000;
//	uint32_t volatile *const r2 = (uint32_t*) 0x20001004;
//
//
//	*r1 = 3;
//	*r2 = 6;

	__asm volatile("LDR R0, [R1]");
	__asm volatile("LDR R1, [R2]");
	__asm volatile("ADD R0, R0,  R1");
	__asm volatile("STR R0, [R2]");
}

void assembly2() {

	uint32_t val1 = 5;
	uint32_t val2 = 2;
	__asm volatile("MOV R0, %0" : : "r"(val1));
	__asm volatile("MOV R1, %0" : : "r"(val2));
	__asm volatile("MOV R2, %0" : : "i"(0x3));

}
int main(void) {

//	assembly1();
//	assembly2();

	uint32_t controlRegister;
	//write only destination register "=r"
	__asm volatile("MRS %0, CONTROL": "=r"(controlRegister));

	uint32_t src = 50;
	uint32_t dest;

	__asm volatile("MOV %0, %1": "=r"(dest): "r"(src));

}

