/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 * - CortexMx -
 * 	- 15 total exceptions
 * 	- 240 interrupts
 *	- 255 total exceptions
 *
 * - System exceptions?
 * 	- Exception - generated by processor
 * 	- Interrupts- from external world to processor
 *	- Both fall under "exceptions"
 *
 * - Whenever processor receives exception it changes to handler mode
 *
 * - Different system exceptions
 * 		- Exception #1 - ( RESET exception or system exception )
 *		- Only 9 implemented system exceptions, 6 reserved for future
 *			- check again with documents
 *		- Exception #16 is Interrupt 1 (IRQ)
 *
 * - All Processor Peripherals use PPB bus
 *
 * - System Exception Control Registers
 *		- System Control Block Peripheral
 *			 - controls and configure system exceptions
 *
 * - NVIC (nested vector interrupt controller)
 *	- peripheral in processor
 *	- used to configure 240 interrupts
 *	- Enable/Disable/Pend various interrupts
 *	- Configure priority of interrupts
 *	- "Nested"
 *			- b/c it supports pre-empting lower priority interrupt handler
 *			- when higher priority interrupt arrives
 *
 *	- STMF407 = has 83  different interrupts (vendor specific)
 *	- Interrupts are designed by microcontroller
 *		- ARM Cortex Mx allows max 240 interrupts in NVIC
 *			- microcontroller vendor chooses how to connect it
 *
 *	- IRQ numbers = number it is connected on to NVIC line
 *		EX: GPIO connected to NVIC line 0, GPIO_IRQ = 0
 *
 */


int main(void) {
	/* Loop forever */
	for (;;)
		;
}
