/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 *
 *
 * Notes:
 * 		- 2 important system level services:
 *
 * 		 - SVC (SuperVisor call)
 *			- typically used to request privileged operations or
 *	access to system resources from OS
 *
 *		- SVC is mainly used in OS env. EX: a less priv user task
 *				can trigger SVC execetion to get system level services
 *				like (access device drivers)
 *
 *		- PendSv is mainly used in OS to carry context switch
 *			between 2 or more tasks when no other exceptions are active in system
 *
 *
 *
 *
 *
 */

int main(void) {
	/* Loop forever */
	for (;;)
		;
}
