
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include "main.h"

int main(void) {
	RCC_AHB1ENR_t volatile *const ppRcc = (RCC_AHB1ENR_t*) 0x40023830;
	GPIOx_MODE_t volatile *const ppGpioOutModeReg = (GPIOx_MODE_t*) 0x40020C00;
	GPIOx_ODR_t volatile *const ppGpioOutDataReg = (GPIOx_ODR_t*) 0x40020C14;

	//1. turn on the GPIOD peripheral clock
	ppRcc->gpiod_en = 1;

	//2. configure the mode of the IO pin as output
	ppGpioOutModeReg->pin_12 = 1;

	//3. Configure the 12th bit (corresponding to 12th pin) of GPIOD output data to 1 (HIGH);
	ppGpioOutDataReg->pin_12 = 1;
}
