/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include <stdio.h>

int main(void) {

	uint32_t *const ppRcc = (uint32_t*) 0x40023830;
	uint32_t *const ppGpioOutModeReg = (uint32_t*) 0x40020C00;
	uint32_t *const ppGpioOutDataReg = (uint32_t*) 0x40020C14;

	*ppRcc |= (1 << 3);

	*ppGpioOutModeReg &= ~(1 << 24);
	*ppGpioOutModeReg &= ~(1 << 25);
	*ppGpioOutModeReg &= ~(1 << 26);
	*ppGpioOutModeReg &= ~(1 << 27);
	*ppGpioOutModeReg &= ~(1 << 28);
	*ppGpioOutModeReg &= ~(1 << 29);
	*ppGpioOutModeReg &= ~(1 << 30);
	*ppGpioOutModeReg &= ~(1 << 31);

	*ppGpioOutModeReg |= (1 << 24);
	*ppGpioOutModeReg |= (1 << 26);
	*ppGpioOutModeReg |= (1 << 28);
	*ppGpioOutModeReg |= (1 << 30);

	/* Loop forever */
	uint64_t i = 0;
	printf("Turning  on Green light");
	while (i <= 10) {
//		printf("Turning  on Green light");
		*ppGpioOutDataReg |= (1 << 12);
		for (uint32_t i = 0; i < 900000; i++)
			;
		*ppGpioOutDataReg &= ~(1 << 12);
		printf("Turn  on Orange light");
		*ppGpioOutDataReg |= (1 << 13);
		for (uint32_t i = 0; i < 900000; i++)
			;
		*ppGpioOutDataReg &= ~(1 << 13);
		printf("Turn  on Red light");
		*ppGpioOutDataReg |= (1 << 14);
		for (uint32_t i = 0; i < 900000; i++)
			;
		*ppGpioOutDataReg &= ~(1 << 14);
		printf("Turn  on Blue light");
		*ppGpioOutDataReg |= (1 << 15);
		for (uint32_t i = 0; i < 900000; i++)
			;
		*ppGpioOutDataReg &= ~(1 << 15);
		i++;

	};

}

