/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

int main(void) {
	//ADDRESS OF RCC-GPIOD register to activate GPIOD clock peripheral
	//0x40023800(base)  +  0x30 (offset) = 0x40023830

	//ADDRESS OF GPIOD output mode register (used to control mode)
	//0x40020C00 ( base ) + 0x00   (offset) = 0x40020C00

	//ADDRESS OF GPIOD output data register (used to write)
	//0x40020C00 ( base ) + 0x14   (offset) = 0x40020C14

	uint32_t *const pRcc = (uint32_t*) 0x40023830;
	uint32_t *const pGpioOutModeReg = (uint32_t*) 0x40020C00;
	uint32_t *const pGpioOutDataReg = (uint32_t*) 0x40020C14;

	//1. Enable the clock for GPIOD Peripheral  in in the AHB1ENR bus

	//mask value to turn the 3rd bit to 1, which will enable the GPIOD peripheral clock
	//in the RCC register
	//0x00000008 = 3rd bit is 1 in OR bitwise operation

	*pRcc |= 0x08;

	//2. Configure the GPIOD pin as output (each pin consists of 2 bits)

	//a. Clear both 12th pin bits (24,25) = 00 (&)
	*pGpioOutModeReg &= 0xFCFFFFFF;

	//b.Set 12th pin bits (24,25) to output mode = 01 (|), 25th bit =0, 24 = 0
	*pGpioOutModeReg |= 0x01000000;

	//3. Configure the 12th bit (corresponding to 12th pin) of GPIOD output data to 1 (HIGH);
	*pGpioOutDataReg |= 0x1000;

//	/* Loop forever */
//	while (1);

	//will need to reset these registers before doing this

	//using bitwise shift operators

	uint32_t *const ppRcc = (uint32_t*) 0x40023830;
	uint32_t *const ppGpioOutModeReg = (uint32_t*) 0x40020C00;
	uint32_t *const ppGpioOutDataReg = (uint32_t*) 0x40020C14;

	*ppRcc |= (1 << 3);

	//2. Configure the GPIOD pin as output (each pin consists of 2 bits)

	//a. Clear both 12th pin bits (24,25) = 00 (&)
	*ppGpioOutModeReg &= ~(1 << 24);
	*ppGpioOutModeReg &= ~(1 << 25);

	// OR
//	*ppGpioOutModeReg &= ~(3 << 24);

	//b.Set 12th pin bits (24,25) to output mode = 01 (|), 25th bit =0, 24 = 0
	*ppGpioOutModeReg |= (1 << 24);

	//3. Configure the 12th bit (corresponding to 12th pin) of GPIOD output data to 1 (HIGH);
	*ppGpioOutDataReg |= (1 << 12);

	/* Loop forever */
//	while (1);

}

